### ISSUE TITLE
Please restore the swap widget on the website

### ISSUE THREAD

**Issue by icy-ux** [UnstoppableSwap/unstoppableswap-site#8]
Please restore the swap widget which was [recently removed](https://github.com/UnstoppableSwap/unstoppableswap-site/commit/aac9f6f134fa1ac6028f40258922fe964d4b16b6#diff-0aa28f907d48430097fbb2a214f77ff4892f8c4fafad22cce6bd315f86e6169c) from the website.

Right now rendezvous-based seller discovery is [not working reliably](https://github.com/comit-network/xmr-btc-swap/issues/1414) and many people do know how to use the command line so the swap widget is currently the only reliable way for command-line swap users to find sellers.

**Comment by icy-ux** [comment]
Based on [other issues](https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/149) I really don't think new users should be steered towards the GUI, it needs a lot more testing.

**Comment by binarybaron** [comment]
Sounds reasonable. Will do

**Comment by binarybaron** [comment]
Fixed with https://github.com/UnstoppableSwap/unstoppableswap-site/commit/6db3cd4d7be6775f755146c5f275e567e01e566e
